"""Expose Cognityx Ingest's deliberate stable Python composition surface.

This module exists so applications can import supported SourceAsset, ingestion,
artifact, and canonical-content APIs without depending on internal file layout.
It performs no processing itself: the core mechanism is explicit re-export of
approved public records and services. The design principle is compatibility by
addition, which is why the v3.2 ``CanonicalRepresentation`` alias does not replace
the established enrichment ``Representation`` name. CLI adapters, DataForge,
audit tooling, tests, and direct Python integrators use this surface.
"""

from cognityx_ingest.canonical_content import (
    CANONICAL_CONTENT_SCHEMA_VERSION,
    CanonicalArtifactDescriptor,
    CanonicalContentArtifact,
    CanonicalContentBuilder,
    CanonicalContentError,
    CanonicalContentValidationError,
    CanonicalOwnershipError,
    CanonicalReferenceError,
    CanonicalRelation,
    CanonicalResource,
    CanonicalText,
    ContentNode,
    Division,
    NativeBinding,
    NativeBindingValidationError,
    PresentationUnit,
    ProcessingActivity,
    Representation as CanonicalRepresentation,
    SourceSelector,
)
from cognityx_ingest.context import resolve_execution_context
from cognityx_ingest.cleanup import SourceAssetCleanupService
from cognityx_ingest.control import (
    ControlClient,
    ControlDecision,
    IngestAuthorizationError,
    IngestLimitError,
    LocalControlClient,
)
from cognityx_ingest.management import IngestManager
from cognityx_ingest.enhancement import (
    BoundedInferenceResolver,
    InferenceResolutionConfig,
    InferenceTarget,
    ResolutionTask,
)
from cognityx_ingest.enrichment import (
    EnrichmentCatalog,
    EnrichmentIdentity,
    IndexBinding,
    KnowledgeUnit,
    Representation,
    RetrievalUnit,
)
from cognityx_ingest.models import (
    ArtifactRef,
    Block,
    CanonicalDocument,
    DecisionRecord,
    DocumentObject,
    DocBundle,
    DocBundleDeletionResult,
    Evidence,
    IngestJobState,
    IngestResult,
    IngestRunResult,
    PageRecord,
    Relation,
    RepeatedRegion,
    RepeatedRegionOccurrence,
    RegisteredSource,
    Section,
    SourceAsset,
    SourceAssetBatchItem,
    SourceAssetBatchResult,
    SourceAssetContext,
    SourceAssetDeletionResult,
    SourceAssetLocation,
    SourceAssetRegistrationResult,
    SourceBundle,
    SourceContext,
    SourceLocation,
    SourceRecord,
    TableCell,
    TablePart,
    TableRow,
    SourceRegistrationResult,
    SourceAnchor,
    UnresolvedItem,
    UsageReport,
)
from cognityx_ingest.native_artifacts import (
    NativeArtifactConflictError,
    NativeArtifactDescriptor,
    NativeArtifactError,
    NativeArtifactIntegrityError,
    NativeArtifactNotFoundError,
    NativeArtifactStore,
    NativePointerError,
    ReloadedNativeArtifact,
)
from cognityx_ingest.parser import (
    BasicPdfParser,
    DoclingParser,
    ExtractedBlock,
    ExtractedObject,
    ExtractedPage,
    ExtractedRelation,
    ExtractedSection,
    ExtractionPolicy,
    ExtractionResult,
    ParserRouter,
    ParserUnavailableError,
    PyMuPDFParser,
    PyPdfExtractor,
    UnsupportedInputError,
)
from cognityx_ingest.service import IngestService
from cognityx_ingest.source_assets import (
    SourceAssetBatchCancelled,
    SourceAssetCatalogAmbiguityError,
    SourceAssetCatalogError,
    SourceAssetRegistry,
)
from cognityx_ingest.sources import SourceRegistry
from cognityx_resource import ExecutionContext, ResourceContext, ResourceRef

__all__ = [
    "ArtifactRef",
    "BasicPdfParser",
    "Block",
    "BoundedInferenceResolver",
    "CANONICAL_CONTENT_SCHEMA_VERSION",
    "CanonicalArtifactDescriptor",
    "CanonicalContentArtifact",
    "CanonicalContentBuilder",
    "CanonicalContentError",
    "CanonicalContentValidationError",
    "CanonicalDocument",
    "CanonicalOwnershipError",
    "CanonicalReferenceError",
    "CanonicalRelation",
    "CanonicalRepresentation",
    "CanonicalResource",
    "CanonicalText",
    "ControlClient",
    "ControlDecision",
    "ContentNode",
    "DecisionRecord",
    "DocBundle",
    "DocBundleDeletionResult",
    "DoclingParser",
    "DocumentObject",
    "Division",
    "EnrichmentCatalog",
    "EnrichmentIdentity",
    "Evidence",
    "ExecutionContext",
    "ExtractedBlock",
    "ExtractedObject",
    "ExtractedPage",
    "ExtractedRelation",
    "ExtractedSection",
    "ExtractionPolicy",
    "ExtractionResult",
    "IngestAuthorizationError",
    "IngestJobState",
    "IngestLimitError",
    "IngestManager",
    "IngestResult",
    "IngestRunResult",
    "IngestService",
    "IndexBinding",
    "InferenceResolutionConfig",
    "InferenceTarget",
    "KnowledgeUnit",
    "LocalControlClient",
    "NativeArtifactConflictError",
    "NativeArtifactDescriptor",
    "NativeArtifactError",
    "NativeArtifactIntegrityError",
    "NativeArtifactNotFoundError",
    "NativeArtifactStore",
    "NativeBinding",
    "NativeBindingValidationError",
    "NativePointerError",
    "PageRecord",
    "ParserRouter",
    "ParserUnavailableError",
    "PyMuPDFParser",
    "PyPdfExtractor",
    "PresentationUnit",
    "ProcessingActivity",
    "Relation",
    "RepeatedRegion",
    "RepeatedRegionOccurrence",
    "ReloadedNativeArtifact",
    "RegisteredSource",
    "Representation",
    "ResolutionTask",
    "ResourceContext",
    "ResourceRef",
    "RetrievalUnit",
    "Section",
    "SourceAsset",
    "SourceAssetBatchCancelled",
    "SourceAssetBatchItem",
    "SourceAssetBatchResult",
    "SourceAssetContext",
    "SourceAssetCleanupService",
    "SourceAssetDeletionResult",
    "SourceAssetCatalogAmbiguityError",
    "SourceAssetCatalogError",
    "SourceAssetLocation",
    "SourceAssetRegistrationResult",
    "SourceAssetRegistry",
    "TableCell",
    "TablePart",
    "TableRow",
    "SourceBundle",
    "SourceContext",
    "SourceLocation",
    "SourceRecord",
    "SourceSelector",
    "SourceRegistrationResult",
    "SourceAnchor",
    "SourceRegistry",
    "UnsupportedInputError",
    "UnresolvedItem",
    "UsageReport",
    "resolve_execution_context",
]
