"""Focused parser-neutral canonical contract checks for completed T02.

The suite proves frozen projection fidelity, text-once ownership, distinct
presentation and logical structure, deterministic direct/subtree reconstruction,
and unchanged v2 Python behavior. Frozen expected files remain authoritative and
are never regenerated by these tests.
"""

from __future__ import annotations

import json
import hashlib
from pathlib import Path

from cognityx_ingest import (
    CANONICAL_CONTENT_SCHEMA_VERSION,
    Block,
    CanonicalContentArtifact,
    CanonicalContentBuilder,
    CanonicalDocument,
    CanonicalResource,
    CanonicalText,
    ContentNode,
    Division,
    IngestService,
    PageRecord,
    PresentationUnit,
    PyPdfExtractor,
    SourceAssetRegistry,
    SourceAsset,
    SourceRecord,
    SourceSelector,
    Section,
)
from cognityx_resource import ExecutionContext
from cognityx_storage import LocalStorageBackend, StorageClient, StorageConfig, StorageRuntime


def _ingest(tmp_path: Path, source: Path):
    """Ingest the reused provenance PDF through the current production API."""
    runtime = StorageRuntime.from_config(StorageConfig.built_in(root=tmp_path / "runtime"))
    registry = SourceAssetRegistry.load(runtime=runtime)
    storage = StorageClient(LocalStorageBackend(tmp_path / "artifacts")).for_shared_data()
    context = ExecutionContext(
        run_id="run-canonical",
        correlation_id="cor-canonical",
        principal_id="fixture-test",
    )
    result = IngestService(storage, extractor=PyPdfExtractor(), registry=registry).ingest(
        source, context=context, registry=registry
    )
    return result, storage


def test_canonical_document_still_preserves_current_python_ingest_shape(
    tmp_path: Path, provenance_pdf: Path
) -> None:
    """Verify the existing Python ingest path still returns the v2 document shape."""
    result, storage = _ingest(tmp_path, provenance_pdf)
    payload = json.loads(storage.open(result.provenance_key).read())
    assert result.document.document_id.startswith("pdf-")
    assert payload["document_id"] == result.document.document_id
    assert payload["parser"]["selected"] == "basic"
    assert payload["pages"]
    assert all(
        page["physical_page_index"] == i
        for i, page in enumerate(payload["pages"])
    )


def test_expected_canonical_content_fixture_matches_contract(v3_2_fixture_root: Path) -> None:
    """Assert the frozen v3.2 canonical fixture stores text once per node."""
    content = json.loads(
        (v3_2_fixture_root / "expected" / "canonical_content.json").read_text(
            encoding="utf-8"
        )
    )
    assert content["schema"] == "cognityx.ingest.canonical-content/v3.2"
    texts = [node["content"]["text"] for node in content["content_nodes"]]
    assert texts
    assert len(texts) == len(set(texts))
    assert all(node["source_selectors"] for node in content["content_nodes"])


def test_frozen_canonical_projection_loads_into_complete_records(
    frozen_canonical_artifact: CanonicalContentArtifact,
    v3_2_fixture_root: Path,
) -> None:
    """Match every authoritative fixture resource, node, text, hash, and selector."""
    expected = json.loads(
        (v3_2_fixture_root / "expected" / "canonical_content.json").read_text(
            encoding="utf-8"
        )
    )
    actual_resources = {
        item.resource_id: item for item in frozen_canonical_artifact.resources
    }
    assert frozen_canonical_artifact.schema == expected["schema"]
    assert {
        item["resource_id"]: item["source_sha256"] for item in expected["resources"]
    } == {
        identifier: item.source_sha256
        for identifier, item in actual_resources.items()
    }
    actual_nodes = {
        item.node_id: item for item in frozen_canonical_artifact.content_nodes
    }
    for expected_node in expected["content_nodes"]:
        actual = actual_nodes[expected_node["node_id"]]
        assert actual.resource_id == expected_node["resource_id"]
        assert actual.owner_division_id == expected_node["owner_division_id"]
        assert actual.node_kind == expected_node["node_kind"]
        assert actual.content.text == expected_node["content"]["text"]
        assert actual.content.sha256 == expected_node["content"]["sha256"]
        assert actual.source_selectors[0].source_path == expected_node[
            "source_selectors"
        ][0]["source_path"]
        assert actual.source_selectors[0].char_start == expected_node[
            "source_selectors"
        ][0]["char_start"]
        assert actual.source_selectors[0].char_end == expected_node[
            "source_selectors"
        ][0]["char_end"]


def test_frozen_selectors_reproduce_exact_source_substrings(
    frozen_canonical_artifact: CanonicalContentArtifact,
    v3_2_fixture_root: Path,
) -> None:
    """Use only real frozen ranges to recover every exact authoritative text."""
    for node in frozen_canonical_artifact.content_nodes:
        selector = node.source_selectors[0]
        assert selector.source_path is not None
        assert selector.char_start is not None
        assert selector.char_end is not None
        source = (v3_2_fixture_root / selector.source_path).read_text(
            encoding="utf-8"
        )
        assert source[selector.char_start : selector.char_end] == node.content.text


def test_every_content_node_hashes_exact_utf8_bytes(
    frozen_canonical_artifact: CanonicalContentArtifact,
) -> None:
    """Verify hashes from exact Unicode bytes without normalization or decoding loss."""
    for node in frozen_canonical_artifact.content_nodes:
        assert node.content.sha256 == hashlib.sha256(
            node.content.text.encode("utf-8")
        ).hexdigest()


def test_one_division_record_supports_extensible_logical_roles() -> None:
    """Represent document, section, clause, and appendix without role subclasses."""
    divisions = tuple(
        Division(
            division_id=f"div-{role}",
            resource_id="res-one",
            division_role=role,
            parent_division_id=None,
            child_division_ids=(),
            title_node_id=None,
            direct_node_ids=(),
            sequence_number=index,
        )
        for index, role in enumerate(("document", "section", "clause", "appendix"))
    )
    assert {type(item) for item in divisions} == {Division}
    assert [item.division_role for item in divisions] == [
        "document",
        "section",
        "clause",
        "appendix",
    ]


def test_presentation_units_and_divisions_remain_distinct_concepts(
    frozen_canonical_artifact: CanonicalContentArtifact,
) -> None:
    """Keep source surfaces separate from logical hierarchy and copied content."""
    assert frozen_canonical_artifact.presentation_units
    assert frozen_canonical_artifact.divisions
    assert all(isinstance(item, PresentationUnit) for item in frozen_canonical_artifact.presentation_units)
    assert all(isinstance(item, Division) for item in frozen_canonical_artifact.divisions)
    assert all(not hasattr(item, "text") for item in frozen_canonical_artifact.presentation_units)
    assert all(not hasattr(item, "text") for item in frozen_canonical_artifact.divisions)


def test_every_node_has_one_deepest_direct_owner(
    frozen_canonical_artifact: CanonicalContentArtifact,
) -> None:
    """Prove each node appears in exactly its declared direct Division list."""
    direct_owners: dict[str, list[str]] = {}
    for division in frozen_canonical_artifact.divisions:
        for node_id in division.direct_node_ids:
            direct_owners.setdefault(node_id, []).append(division.division_id)
    assert set(direct_owners) == {
        item.node_id for item in frozen_canonical_artifact.content_nodes
    }
    assert all(
        owners == [
            next(
                node.owner_division_id
                for node in frozen_canonical_artifact.content_nodes
                if node.node_id == node_id
            )
        ]
        for node_id, owners in direct_owners.items()
    )


def test_direct_and_subtree_lookup_return_existing_nodes_in_source_order(
    frozen_canonical_artifact: CanonicalContentArtifact,
) -> None:
    """Reconstruct parent content through references without parent text storage."""
    direct = frozen_canonical_artifact.direct_nodes("div-policy-root")
    subtree = frozen_canonical_artifact.subtree_nodes("div-policy-root")
    assert [item.node_id for item in direct] == ["pol-heading-root"]
    assert [item.node_id for item in subtree] == [
        "pol-heading-root",
        "pol-heading-42",
        "pol-p1",
        "pol-p2",
        "pol-p3",
        "pol-p4",
        "pol-heading-71",
        "pol-p5",
    ]
    root = next(
        item
        for item in frozen_canonical_artifact.divisions
        if item.division_id == "div-policy-root"
    )
    assert not hasattr(root, "subtree_text")
    assert not hasattr(root, "text")


def test_source_text_occurs_only_under_content_node_content_text(
    frozen_canonical_artifact: CanonicalContentArtifact,
) -> None:
    """Recursively prove source strings do not leak into any non-content record."""
    payload = frozen_canonical_artifact.to_dict()
    source_texts = {item.content.text for item in frozen_canonical_artifact.content_nodes}
    occurrences: list[tuple[tuple[object, ...], str]] = []

    def visit(value: object, path: tuple[object, ...] = ()) -> None:
        """Collect exact source-string matches without flagging ordinary metadata."""
        if isinstance(value, dict):
            for key, item in value.items():
                visit(item, (*path, key))
        elif isinstance(value, list):
            for index, item in enumerate(value):
                visit(item, (*path, index))
        elif isinstance(value, str) and value in source_texts:
            occurrences.append((path, value))

    visit(payload)
    assert len(occurrences) == len(frozen_canonical_artifact.content_nodes)
    assert all(
        len(path) == 4
        and path[0] == "content_nodes"
        and isinstance(path[1], int)
        and path[2:] == ("content", "text")
        for path, _text in occurrences
    )


def test_equal_text_at_distinct_selectors_remains_two_occurrences() -> None:
    """Keep repeated passages distinct because selectors, not hashes, own identity."""
    text = "Repeated policy sentence."
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    nodes = tuple(
        ContentNode(
            node_id=f"node-{index}",
            resource_id="res-repeat",
            owner_division_id="div-repeat",
            node_kind="paragraph",
            content=CanonicalText(text=text, sha256=digest),
            source_selectors=(
                SourceSelector(
                    selector_id=f"selector-{index}",
                    selector_type="text-position",
                    resource_id="res-repeat",
                    source_path="sources/repeated.txt",
                    char_start=index * 30,
                    char_end=index * 30 + len(text),
                ),
            ),
            sequence_number=index,
        )
        for index in range(2)
    )
    artifact = CanonicalContentArtifact(
        schema=CANONICAL_CONTENT_SCHEMA_VERSION,
        document_id="doc-repeat",
        resources=(
            CanonicalResource(
                resource_id="res-repeat",
                source_asset_id="src-repeat",
                source_sha256="0" * 64,
                media_type="text/plain",
                original_filename="repeated.txt",
                logical_uri="sourceasset://src-repeat",
            ),
        ),
        presentation_units=(),
        divisions=(
            Division(
                division_id="div-repeat",
                resource_id="res-repeat",
                division_role="document",
                parent_division_id=None,
                child_division_ids=(),
                title_node_id=None,
                direct_node_ids=("node-0", "node-1"),
                sequence_number=0,
            ),
        ),
        content_nodes=nodes,
        representations=(),
        native_bindings=(),
        relations=(),
        processing_activities=(),
        artifact_descriptors=(),
    )
    artifact.validate()
    assert nodes[0].content.sha256 == nodes[1].content.sha256
    assert nodes[0].node_id != nodes[1].node_id
    assert nodes[0].source_selectors != nodes[1].source_selectors


def test_builder_assigns_child_blocks_to_deepest_explicit_section() -> None:
    """Choose logical child membership over parent span overlap or page location."""
    document_id = "doc-deepest-owner"
    page_id = f"{document_id}:page:0"
    blocks = tuple(
        Block(
            block_id=f"block-{index}",
            page_id=page_id,
            block_type=("heading" if index in {0, 2} else "paragraph"),
            reading_order=index,
            text=text,
        )
        for index, text in enumerate(
            (
                "1. Parent",
                "Parent direct text.",
                "1.1 Child",
                "Child direct text.",
                "Parent trailing text.",
            )
        )
    )
    parent = Section(
        section_id="section-parent",
        title="Parent",
        number="1",
        level=1,
        parent_section_id=None,
        heading_block_id="block-0",
        evidence_ids=(),
        block_ids=tuple(item.block_id for item in blocks),
    )
    child = Section(
        section_id="section-child",
        title="Child",
        number="1.1",
        level=2,
        parent_section_id=parent.section_id,
        heading_block_id="block-2",
        evidence_ids=(),
        block_ids=("block-2", "block-3"),
    )
    source_asset = SourceAsset(
        source_id="src-deepest-owner",
        context_id="ctx-test",
        bundle_id="bundle-test",
        original_filename="deepest.pdf",
        media_type="application/pdf",
        size_bytes=10,
        sha256="1" * 64,
        blob_id="blob-deepest-owner",
        created_by="fixture-test",
        created_at="2026-08-06T00:00:00Z",
    )
    document = CanonicalDocument(
        document_id=document_id,
        schema_version="cognityx.ingest.document/v2",
        source=SourceRecord(
            source_id=source_asset.asset_id,
            filename=source_asset.original_filename,
            sha256=source_asset.sha256,
            size_bytes=source_asset.size_bytes,
            storage_key=f"sourceasset://{source_asset.asset_id}",
        ),
        title="Deepest",
        sections=(parent, child),
        pages=(
            PageRecord(
                page_id=page_id,
                physical_page_index=0,
                sequence_number=0,
                block_ids=tuple(item.block_id for item in blocks),
            ),
        ),
        blocks=blocks,
    )
    artifact = CanonicalContentBuilder().build(
        document,
        source_asset,
        ExecutionContext(
            run_id="run-deepest-owner",
            correlation_id="cor-deepest-owner",
            principal_id="fixture-test",
        ),
    )
    owners = {item.node_id: item.owner_division_id for item in artifact.content_nodes}
    assert owners["block-0"] == "section-parent"
    assert owners["block-1"] == "section-parent"
    assert owners["block-2"] == "section-child"
    assert owners["block-3"] == "section-child"
    assert owners["block-4"] == "section-parent"
    parent_division = next(
        item for item in artifact.divisions if item.division_id == "section-parent"
    )
    child_division = next(
        item for item in artifact.divisions if item.division_id == "section-child"
    )
    assert parent_division.title_node_id == "block-0"
    assert child_division.title_node_id == "block-2"
    assert "block-3" not in parent_division.direct_node_ids
